name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Download and install Qt
      run: |
        wget https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
        chmod +x qt-unified-linux-x64-online.run
        ./qt-unified-linux-x64-online.run --platform minimal --script tools/qt-installer-noninteractive.qs

    - name: Configure and build
      run: |
        mkdir build
        cd build
        qmake ..
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/
