name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install QtCI scripts
      run: |
        wget https://raw.githubusercontent.com/benlau/qtci/master/recipes/install-qt
        wget https://raw.githubusercontent.com/benlau/qtci/master/bin/extract-qt-installer
        chmod +x install-qt extract-qt-installer

    - name: Install Qt
      run: |
        ./install-qt 5.15.1

    - name: Configure and build
      run: |
        mkdir build
        cd build
        qmake ..
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/
