name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential perl python git

    - name: Download Qt source package
      run: |
        wget https://download.qt.io/archive/qt/5.15/5.15.1/single/qt-everywhere-src-5.15.1.tar.xz
        tar -xf qt-everywhere-src-5.15.1.tar.xz

    - name: Build and install Qt
      run: |
        cd qt-everywhere-src-5.15.1
        ./configure -opensource -confirm-license -release -nomake examples -nomake tests
        make -j$(nproc)
        sudo make install

    - name: Configure and build
      run: |
        mkdir build
        cd build
        qmake ..
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/
