name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0

    - name: Install Qt
      run: |
        wget https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
        chmod +x qt-unified-linux-x64-online.run
        echo "Installing Qt..."
        ./qt-unified-linux-x64-online.run --script tools/qt-installer-noninteractive.qs

    - name: Configure and build
      run: |
        mkdir build
        cd build
        qmake ..
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/
